### ISSUE TITLE
ExecReload redirecting to bad folder

### ISSUE THREAD

**Issue by Booteille** [gplessis/dotdeb-php#100]
Hi.

I faced another issue when installing the package.
The *php7.0-fpm* service is asking for */usr/lib/php/7.0/php7.0-fpm-checkconf* but the file is in the parent folder (actually */usr/lib/php/*).

I had to edit */lib/systemd/system/php7.0-fpm.service* in order to fix it.

**Comment by gplessis** [comment]
This has been fixed in the latest upload
