### ISSUE TITLE
Database PDO modules for PHP 7

### ISSUE THREAD

**Issue by bjoern-vh** [gplessis/dotdeb-php#103]
Hello,

when will the (PDO) modules for Interbase/Firebird, Oracle and SQL Server 2010+ be available? Only roughly estimated. 

Is it possible to use Dotdeb PPA and compile the missing modules from source? Is there any tutorial? 

Thanks a lot in advance.

Kind regards
Bjoern

**Comment by gplessis** [comment]
`php7.0-interbase` and `php7.0-sybase` should be available with the next PHP7 packages update.

**Comment by gplessis** [comment]
Interbase and Sybase are now available with PHP 7.0.8.
