### ISSUE TITLE
Feature Request: APCu for PHP7

### ISSUE THREAD

**Issue by felicitus** [gplessis/dotdeb-php#104]
It would be nice to have the php7.0-apcu module within the dotdeb repository.

**Comment by EAnushan** [comment]
PECL pacakges require some more work, mentioned here: https://www.dotdeb.org/2015/12/04/php-7-0-0-is-available-for-jessie/

**Comment by markushausammann** [comment]
+1

**Comment by aimfeld** [comment]
+1

**Comment by gplessis** [comment]
APCu is now available for PHP 7.0 : `apt-get install php7.0-apcu`

Enjoy :)

**Comment by EAnushan** [comment]
Thank you!

**Comment by EAnushan** [comment]
By the way, PHP 7 apcu module is not backward compatible with apc function calls, as mentioned in this thread: https://github.com/krakjoe/apcu/issues/78#issuecomment-161892728

In PHP 5, the apcu module registers the apc prefix, so functions like `apc_fetch()` continue to work. In PHP 7, that is not done by default. You will have to use `apcu_fetch()` or install the apcu_bc extension.

Do you think you will add the apcd_bc extension to the repo eventually?

**Comment by gplessis** [comment]
@EAnushan `php7.0-apcu-bc` is now available

**Comment by EAnushan** [comment]
@gplessis Thank you, once again.
