### ISSUE TITLE
There's no mongo module

### ISSUE THREAD

**Issue by DavidVentura** [gplessis/dotdeb-php#105]
Hi
I'm using php5-mongo but there's no php7-mongo in the repos

**Comment by EAnushan** [comment]
I mentioned this in the APCu issue as well, but PECL pacakges require some more work, mentioned here: https://www.dotdeb.org/2015/12/04/php-7-0-0-is-available-for-jessie/

I'm waiting for the Xdebug package myself.

**Comment by gplessis** [comment]
The `mongo` extension has been superseded by the `mongodb` PECL module. This one is now available as `php7.0-mongodb`.
