### ISSUE TITLE
Imagick, memcache extension for php7.0

### ISSUE THREAD

**Issue by harshadyeola** [gplessis/dotdeb-php#106]
I can not see php7.0 build includes `php7.0-imagick` `php7.0-memcache`package. Is there any chance to make this available ?

**Comment by gplessis** [comment]
`php7.0-imagick` and `php7.0-memcached` are now available. I'll see what I can do for `php7.0-memcache`.

**Comment by MattyLB** [comment]
:100: thank you!

**Comment by Jean85** [comment]
Imagick package tested, it seems to work, thanks a lot!

**Comment by gplessis** [comment]
The `memcache` PECL extension is not maintained anymore. Please install `php7.0-memcached` instead.
