### ISSUE TITLE
php7.0-intl built with old ICU version 52.1

### ISSUE THREAD

**Issue by AlexGx** [gplessis/dotdeb-php#107]
php7.0-intl built with old ICU version 52.1, which has outdated timezone data and some other issues. Please build with actual ICU version (55.1, 56.1 еtc).

**Comment by gplessis** [comment]
Sorry, but I won't backport a more recent version of ICU than Jessie's one : https://packages.debian.org/jessie/libicu-dev

**Comment by AlexGx** [comment]
There is no need of backport, just recompile with actual version. It builds with no problem on mac.
ICU52 was released 2 years ago, has several bugs & issues, outdated timezone data etc. Its not suitable for modern php apps.

**Comment by AlexGx** [comment]
How to build with actual ICU version (tested on debian 8.2):

wget http://download.icu-project.org/files/icu4c/56.1/icu4c-56_1-src.tgz
tar xvzf icu4c-56_1-src.tgz
cd icu/source
./configure --prefix=/opt/icu4c-php && make && make install


Add to php build config
--with-icu-dir=/opt/icu4c-php


make etc.

thats all =)
