### ISSUE TITLE
(reopen) php7.0-intl built with old ICU version 52.1

### ISSUE THREAD

**Issue by AlexGx** [gplessis/dotdeb-php#109]
I have to "reopen" issue #107 (see also my new comments) , because of all apps that uses intl in timezones that has changed since old ICU 52.1 released works incorrect in date-time related stuff.

Or add to your website note that in your package build used old ICU version, and if actual ICU version needed, manual intl ext rebuild must be done.

Excuse me for molestation =)

**Comment by gplessis** [comment]
Sorry, but I will NOT backport libicu to get the right bindings with PHP. I'll stick to Jessie's version.
