### ISSUE TITLE
php7.0: mcrypt

### ISSUE THREAD

**Issue by Rayzilt** [gplessis/dotdeb-php#110]
php7.0-mcrypt is an available package but it seems that mcrypt is already available in php7.0

If php7.0-mcrypt is installed, this warning is displayed: PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0

php -v output when php7.0-mcrypt package is installed;

    root@server:/# php -v
    PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
    PHP 7.0.1-1~dotdeb+8.1 (cli) NTS
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

php -m output after removal of package:

    root@riddler:/# php -m
    [PHP Modules]
    bcmath
    bz2
    calendar
    Core
    ctype
    curl
    date
    dba
    dom
    enchant
    exif
    fileinfo
    filter
    ftp
    gd
    gettext
    gmp
    hash
    iconv
    intl
    json
    libxml
    mbstring
    mcrypt
    mysqli
    mysqlnd
    openssl
    pcntl
    pcre
    PDO
    pdo_mysql
    Phar
    posix
    Reflection
    session
    SimpleXML
    soap
    sockets
    SPL
    standard
    sysvmsg
    sysvsem
    sysvshm
    tokenizer
    xml
    xmlreader
    xmlwriter
    xsl
    Zend OPcache
    zip
    zlib

    [Zend Modules]
    Zend OPcache

Debian version 8.2

    root@riddler:/# dpkg -l 'php*' | grep '^.i'
    ii  php-common      14-1~dotdeb+8.1    all          Common files for PHP packages
    ii  php-tcpdf       6.0.093+dfsg-1     all          PHP class for generating PDF files on-the-fly
    ii  php7.0          7.0.1-1~dotdeb+8.1 all          server-side, HTML-embedded scripting language         (metapackage)
    ii  php7.0-bz2      7.0.1-1~dotdeb+8.1 amd64        bzip2 module for PHP
    ii  php7.0-cli      7.0.1-1~dotdeb+8.1 amd64        command-line interpreter for the PHP scripting language
    ii  php7.0-common   7.0.1-1~dotdeb+8.1 all          Common files for packages built from the PHP source
    ii  php7.0-curl     7.0.1-1~dotdeb+8.1 amd64        CURL module for PHP
    ii  php7.0-fpm      7.0.1-1~dotdeb+8.1 amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
    ii  php7.0-gd       7.0.1-1~dotdeb+8.1 amd64        GD module for PHP
    ii  php7.0-intl     7.0.1-1~dotdeb+8.1 amd64        Internationalisation module for PHP
    ii  php7.0-json     7.0.1-1~dotdeb+8.1 amd64        JSON module for PHP
    ii  php7.0-mysql    7.0.1-1~dotdeb+8.1 amd64        MySQL module for PHP
    ii  php7.0-opcache  7.0.1-1~dotdeb+8.1 amd64        Zend OpCache module for PHP

**Comment by gplessis** [comment]
It has been fixed with PHP 7.0.2 packages.
