### ISSUE TITLE
libapache2-mod-php5 can't get updated

### ISSUE THREAD

**Issue by TheRojam** [gplessis/dotdeb-php#111]
If i want to update libapache2-mod-php5 i get this error message. 
`The following packages have unmet dependencies:
 libapache2-mod-php5 : Depends: php5-common (= 5.4.45-1~dotdeb+7.1) but 5.4.44-1~dotdeb+7.1 is to be installed`
Also i cannot update php5-common, because its not available.
Last time i uninstalled php5-common and re-installed it, but i do not like to do this everytime.

**Comment by gplessis** [comment]
Could you please provide [some more context](https://www.dotdeb.org/2012/08/24/how-to-post-useful-bug-reports/)?

**Comment by TheRojam** [comment]
**What is your distribution?** Debian old-stable
**What is your architecture?** amd64
**Which exact PHP version are you using?** PHP Version 5.4.44-1~dotdeb+7.1
**Which SAPI are you using?** mod_php
**What’s the full content of your /etc/apt/sources.list and /etc/apt/sources.list.d files?**
 /etc/apt/sources.list:
`deb http://mirror-eu.oneandone.net/linux/distributions/debian/debian wheezy main contrib non-free
deb http://mirror-eu.oneandone.net/linux/distributions/debian/debian-security wheezy/updates main contrib non-free

# deb http://dotdeb.netmirror.org/ stable all
# deb-src http://dotdeb.netmirror.org/ stable all
deb http://packages.dotdeb.org wheezy all
deb-src http://packages.dotdeb.org wheezy all
deb http://packages.prosody.im/debian wheezy main`
*/etc/apt/sources.list.d/nodesource.list:*
`deb https://deb.nodesource.com/node_4.x wheezy main
deb-src https://deb.nodesource.com/node_4.x wheezy main`
*/etc/apt/sources.list.d/wheezy-backports.list:*
`deb http://http.debian.net/debian wheezy-backports main`
**What is the result of dpkg -l 'php*' | grep '^.i' ?**
`ii  php-pear                              5.4.44-1~dotdeb+7.1                             all          PEAR - PHP Extension and Application Repository
ii  php5-cli                              5.4.44-1~dotdeb+7.1                             amd64        command-line interpreter for the php5 scripting language
ii  php5-common                           5.4.44-1~dotdeb+7.1                             amd64        Common files for packages built from the php5 source
ii  php5-curl                             5.4.44-1~dotdeb+7.1                             amd64        CURL module for php5
ii  php5-gd                               5.4.44-1~dotdeb+7.1                             amd64        GD module for php5
ii  php5-mcrypt                           5.4.44-1~dotdeb+7.1                             amd64        MCrypt module for php5
ii  php5-mysql                            5.4.44-1~dotdeb+7.1                             amd64        MySQL module for php5
ii  php5-sqlite                           5.4.44-1~dotdeb+7.1                             amd64        SQLite module for php5
ii  phpmyadmin                            4:3.4.11.1-2+deb7u1                             all          MySQL web administration tool`
**Please provide a textual description of the bug (don’t hesitate to provide some code, the expected result…).** see above.

**Comment by gplessis** [comment]
With the exact same setup as you, I don't have the issue : 
```
root@037e3b221b62:/# dpkg -l '*php*' | grep '^.i'
ii  libapache2-mod-php5             5.4.44-1~dotdeb+7.1       amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-pear                        5.4.44-1~dotdeb+7.1       all          PEAR - PHP Extension and Application Repository
ii  php5-cli                        5.4.44-1~dotdeb+7.1       amd64        command-line interpreter for the php5 scripting language
ii  php5-common                     5.4.44-1~dotdeb+7.1       amd64        Common files for packages built from the php5 source
ii  php5-curl                       5.4.44-1~dotdeb+7.1       amd64        CURL module for php5
ii  php5-gd                         5.4.44-1~dotdeb+7.1       amd64        GD module for php5
ii  php5-mcrypt                     5.4.44-1~dotdeb+7.1       amd64        MCrypt module for php5
ii  php5-mysql                      5.4.44-1~dotdeb+7.1       amd64        MySQL module for php5
ii  php5-sqlite                     5.4.44-1~dotdeb+7.1       amd64        SQLite module for php5
ii  phpmyadmin                      4:3.4.11.1-2+deb7u2       all          MySQL web administration tool
```

```
root@037e3b221b62:/# apt-get install -y libapache2-mod-php5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  php5-cli php5-common php5-curl php5-gd php5-mcrypt php5-mysql php5-sqlite
The following packages will be upgraded:
  libapache2-mod-php5 php5-cli php5-common php5-curl php5-gd php5-mcrypt php5-mysql php5-sqlite
8 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 6341 kB of archives.
After this operation, 9216 B of additional disk space will be used.
Get:1 http://packages.dotdeb.org/ wheezy/all php5-cli amd64 5.4.45-1~dotdeb+7.1 [2674 kB]
Get:2 http://packages.dotdeb.org/ wheezy/all libapache2-mod-php5 amd64 5.4.45-1~dotdeb+7.1 [2789 kB]
Get:3 http://packages.dotdeb.org/ wheezy/all php5-sqlite amd64 5.4.45-1~dotdeb+7.1 [30.8 kB]
Get:4 http://packages.dotdeb.org/ wheezy/all php5-mysql amd64 5.4.45-1~dotdeb+7.1 [80.8 kB]
Get:5 http://packages.dotdeb.org/ wheezy/all php5-mcrypt amd64 5.4.45-1~dotdeb+7.1 [16.1 kB]
Get:6 http://packages.dotdeb.org/ wheezy/all php5-gd amd64 5.4.45-1~dotdeb+7.1 [100 kB]
Get:7 http://packages.dotdeb.org/ wheezy/all php5-curl amd64 5.4.45-1~dotdeb+7.1 [29.5 kB]
Get:8 http://packages.dotdeb.org/ wheezy/all php5-common amd64 5.4.45-1~dotdeb+7.1 [620 kB]
Fetched 6341 kB in 4s (1430 kB/s)    
(...)
root@037e3b221b62:/# dpkg -l '*php*' | grep '^.i'
ii  libapache2-mod-php5             5.4.45-1~dotdeb+7.1       amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-pear                        5.4.44-1~dotdeb+7.1       all          PEAR - PHP Extension and Application Repository
ii  php5-cli                        5.4.45-1~dotdeb+7.1       amd64        command-line interpreter for the php5 scripting language
ii  php5-common                     5.4.45-1~dotdeb+7.1       amd64        Common files for packages built from the php5 source
ii  php5-curl                       5.4.45-1~dotdeb+7.1       amd64        CURL module for php5
ii  php5-gd                         5.4.45-1~dotdeb+7.1       amd64        GD module for php5
ii  php5-mcrypt                     5.4.45-1~dotdeb+7.1       amd64        MCrypt module for php5
ii  php5-mysql                      5.4.45-1~dotdeb+7.1       amd64        MySQL module for php5
ii  php5-sqlite                     5.4.45-1~dotdeb+7.1       amd64        SQLite module for php5
ii  phpmyadmin                      4:3.4.11.1-2+deb7u2       all          MySQL web administration tool
```
All the PHP packages from Dotdeb have been upgraded

**Comment by rraptorr** [comment]
If it is wheezy installation then don't the 'stable' lines (jessie) in sources.list cause problems?

**Comment by gplessis** [comment]
Yes, definitely : stable refers to Jessie, oldstable to Wheezy. You should use distribution names explicitly instead of their *stable aliases.

**Comment by gplessis** [comment]
@TheRojam any feedback on this issue after modifying your `sources.list` ?

**Comment by TheRojam** [comment]
same problem as before.

Am 17.01.2016 um 04:56 schrieb Guillaume Plessis:

**Comment by gplessis** [comment]
It's odd. Could you please use `dselect`or `aptitude` to see exactly which dependency causes the problem?

**Comment by gplessis** [comment]
@TheRojam Any feedback so far?

**Comment by TheRojam** [comment]
same problem....
The following packages have unmet dependencies:
 libapache2-mod-php5 : Depends: php5-common (= 5.4.45-1~dotdeb+7.1) but 5.4.44-1~dotdeb+7.1 is to be installed
E: Unable to correct problems, you have held broken packages.

But i will now deinstall all depends and re-install them

**Comment by gplessis** [comment]
Please keep us posted. Thanks.

**Comment by TheRojam** [comment]
as i assumed - after reinstall i do not have any problem more - as before.
next update of libapache2-mod-php5 i will have the same problem.

**Comment by gplessis** [comment]
Feel free to re-open this issue when it happens.
