### ISSUE TITLE
In 7.0 php-config sed does not replace SAPI-s

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-php#113]
Shell variables don't expand in single quotes.
https://github.com/gplessis/dotdeb-php/blob/616c8cb68aee9a8dd20a90e83d7b280fa98e6e74/debian/patches/0031-expose_all_built_and_installed_apis.patch#L36

And upstream bug?

**Comment by gplessis** [comment]
Thanks for reporting this, I'll propose an upstream fix.

**Comment by gplessis** [comment]
Fixed in 342b1a208b4e53b6632aea27e028f74224a2b5c0. Thanks for your help.
