### ISSUE TITLE
Support of "shmop" (Shared Memory) in php7.0

### ISSUE THREAD

**Issue by yvann** [gplessis/dotdeb-php#114]
Hi,

Could you add the support of "shared memory" methods in php 7.0 ? 
PHP has to be compiled with "--enable-shmop"

Very useful, with https://github.com/kriswallsmith/spork for exemple.

**Comment by Jean85** [comment]
:+1: 
I would need it too, for the same reason!

**Comment by orchestrate8D** [comment]
Have the same issue...

**Comment by jverdeyen** [comment]
👍

**Comment by gplessis** [comment]
shmop is now available with PHP 7.0.8.
