### ISSUE TITLE
Update php-pear for PHP7

### ISSUE THREAD

**Issue by acasademont** [gplessis/dotdeb-php#115]
Hi!

It seems like the php-pear package depends on php5-common, so I can't install it and I can't use the "pecl" command to compile extensions.

Thanks!

**Comment by gplessis** [comment]
Thanks to Jessie's latest update, PHP 5.6 (including `php-pear`, from Debian) and PHP 7.0 (from Dotdeb) are now co-installable on the same machine. Could you please confirm that it fixes your issue?

**Comment by acasademont** [comment]
I am afraid nothing changed with the update to 8.3 :(

```
The following packages have unmet dependencies:
 php-pear : Depends: php5-common (>= 5.6.17+dfsg-0+deb8u1~) but it is not going to be installed
            Depends: php5-cli but it is not going to be installed
```

I am missing something?

**Comment by gplessis** [comment]
`php-pear`still depends on php5, but is usable with php7.0 (be sure to use the right `phpize`).

I may provide an updated `php-pear` package in the future to avoid the dependency on php5

**Comment by szepeviktor** [comment]
You may build php-pear for PHP 
easilyhttp://anonscm.debian.org/cgit/pkg-php/php-pear.git/
Be sure to check out submodules.

**Comment by szepeviktor** [comment]
> I may provide an updated php-pear package in the future

Maybe future is today
```bash
git clone --recursive https://anonscm.debian.org/git/pkg-php/php-pear.git
cd php-pear*
dpkg-buildpackage -uc -us -b
```

**Comment by szepeviktor** [comment]
There is discussion on naming.
Maybe `php7.0-pear`?

**Comment by acasademont** [comment]
@szepeviktor why a new name? AFAIK it's only a dependency issue, the code itself could be the same, the problem was that "php-pear" requires "php5-common". Can't an OR depency ("php5-common" OR "php7.0-common") be set?

**Comment by szepeviktor** [comment]
Excuse me, somehow I thought it had version number 10 which higher than 7.

**Comment by szepeviktor** [comment]
Actually it is at v1.10

**Comment by szepeviktor** [comment]
@gplessis It has arrived https://packages.debian.org/sid/php-pear

**Comment by gplessis** [comment]
Dotdeb now provides a `php-pear`package that is fully compatible with PHP7
