### ISSUE TITLE
PHP 5.6 missing patch to co-install with PHP 7.0

### ISSUE THREAD

**Issue by kmdm** [gplessis/dotdeb-php#120]
PHP 5.6 is missing this Debian patch to be co-installable with PHP 7.0

https://anonscm.debian.org/cgit/pkg-php/php.git/commit/?h=master-5.6&id=12c7ba66eb008332c610f415a3bf3173dc8c5a2a

**Comment by gplessis** [comment]
Dotdeb does not provide PHP 5.6 for Jessie because Debian already does. And 5.6 from Debian 8 already includes this patch.
