### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by blubbsy** [gplessis/dotdeb-php#129]
Since the last upgrade i receive error that it cant load some modules and i dont know why (well, actually they are not existent, thats why :P). I Checked the path in the error and the modules are not there, but i also cant find them in another place. 

xxxxx@xxxxx:~$ sudo php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysqlnd.so' - /usr/lib/php/20151012/mysqlnd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo.so' - /usr/lib/php/20151012/pdo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/calendar.so' - /usr/lib/php/20151012/calendar.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/ctype.so' - /usr/lib/php/20151012/ctype.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/exif.so' - /usr/lib/php/20151012/exif.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/fileinfo.so' - /usr/lib/php/20151012/fileinfo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/ftp.so' - /usr/lib/php/20151012/ftp.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/gettext.so' - /usr/lib/php/20151012/gettext.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/iconv.so' - /usr/lib/php/20151012/iconv.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/phar.so' - /usr/lib/php/20151012/phar.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/posix.so' - /usr/lib/php/20151012/posix.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/shmop.so' - /usr/lib/php/20151012/shmop.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sockets.so' - /usr/lib/php/20151012/sockets.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sysvmsg.so' - /usr/lib/php/20151012/sysvmsg.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sysvsem.so' - /usr/lib/php/20151012/sysvsem.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sysvshm.so' - /usr/lib/php/20151012/sysvshm.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/tokenizer.so' - /usr/lib/php/20151012/tokenizer.so: cannot open shared object file: No such file or directory in Unknown on line 0

Greetings

Blubbsy

**Comment by gplessis** [comment]
Could you please give us more details about your environment? https://www.dotdeb.org/2012/08/24/how-to-post-useful-bug-reports/

Which version did you use before the upgrade? Where did the packages come from? I'm asking because most of the `.so` files mentioned in the warnings above shouldn't be loaded on startup or even located on your disk, their features are usually bundled into the SAPI packages (cli, cgi, fpm...)

Did you try to use the `php.ini` file provided with our packages, without any modification?

**Comment by gplessis** [comment]
any feedback?

**Comment by blubbsy** [comment]
sorry, had some stuff to do. Well, i solved the problem (was actually a bug in my php pages that appeared from php 7.0.5 to 7.0.6), but everything works now like a charm. it is strange that i get this error. Owncloud had similar problems (https://github.com/owncloud/core/pull/24343) and fixed it with the last update. 

As you mentioned i dont have the .so packages above on my disk. 


What is your distribution? Debian Jessie
What is your architecture? amd64
Which exact PHP version are you using? PHP Version 7.0.6-1
Which SAPI are you using? FPM
What’s the full content of your /etc/apt/sources.list and /etc/apt/sources.list.d files? Nothing special, except your repository and the rep of mangodb
What is the result of dpkg -l 'php*' | grep '^.i' ?http://pastebin.com/Zp1tJ7Lk

**Comment by gplessis** [comment]
According to the pastern above, the problem comes from the mix of Dotdeb with another repo providing PHP 7.0.6-1
