### ISSUE TITLE
php7.0-mbstring, php7.0-xml & php7.0-zip missing

### ISSUE THREAD

**Issue by PascalReintjens** [gplessis/dotdeb-php#130]
Hello,

I tried to set up Owncloud with php7. The problem I'm running into, is that the owncloud-deps-php7.0 requires php7.0-mbstring, php7.0-xml and php7.0-zip. Is there any chance to get them added?

Thanks :)

**Comment by achterin** [comment]
i have the same problem. would be nice the packages get added. thanks in advance.

**Comment by gplessis** [comment]
These packages are now available with PHP 7.0.8.

**Comment by PascalReintjens** [comment]
Great, thank you :)
