### ISSUE TITLE
wddx

### ISSUE THREAD

**Issue by thierry62** [gplessis/dotdeb-php#132]
Bonjour,
D’abord, merci  pour pour tout ce travail.
Que faut-il faire pour utiliser les fonctions wddx dans php 7 ?
Il faut recompiler ou activer un module.
Merci

**Comment by friek** [comment]
wddx is indeed missing from dotdeb php 7.0 (even up to version 7.0.7). Can it be recompiled with --enable-wddx please?
Thanks.

**Comment by thierry62** [comment]
Oui, il peut-être compilé avec --enable-wddx.
J'ai aussi besoin de wddx dans libapache2-mod-php7.
Merci

**Comment by gplessis** [comment]
wddx is now available with PHP 7.0.8.

**Comment by thierry62** [comment]
Bonjour,
Merci d'avoir pris en considération ma demande.
J'ai mis à jour mes serveur en "PHP Version 7.0.8-1~dotdeb+8.1" mais malheureusement wddx n'est pas présent.
Dans "phpinfo()", je ne retrouve pas les lignes :+1: Cordialement
          wddx
          WDDX Support => enabled
          WDDX Session Serializer => enabled
Cordialement,
Thierry

**Comment by gplessis** [comment]
the wddx functions will be available after installing `php7.0-xml`
