### ISSUE TITLE
Feature request: ssh2 extension

### ISSUE THREAD

**Issue by drsect0r** [gplessis/dotdeb-php#133]
Hi,

It would be awesome if Dotdeb could provide support for the ssh2 extension. 

https://github.com/Sean-Der/pecl-networking-ssh2/
http://pecl.php.net/package/ssh2

Cheers.

**Comment by drsect0r** [comment]
What do you think @gplessis?

**Comment by drsect0r** [comment]
The package on PECL has been updated to support PHP 7.

**Comment by gplessis** [comment]
`php7.0-ssh2` is now available.

**Comment by drsect0r** [comment]
Thank you! @gplessis
