### ISSUE TITLE
PHP 5.4 security release in Debian Wheezy (LTS)

### ISSUE THREAD

**Issue by mig5** [gplessis/dotdeb-php#134]
Hi,

Debian LTS team recently backported a bunch of security patches for PHP 5.4 on Debian Wheezy:

https://lists.debian.org/debian-lts-announce/2016/05/msg00053.html

I know that PHP 5.4 is very old, but I used Dotdeb's PHP 5.4 on some systems in the past, and now it is a bit awkward that Debian's 'official' versions have more recent security fixes, but the version number is lower than Dotdeb's, so it's not so easy to 'downgrade' to get the 'upgrade' so to speak :)

Is there any chance to get those same fixes rolled out for Dotdeb as per your note in https://www.dotdeb.org/2015/09/08/php-5-4-45-for-wheezy-and-squeeze/ 'there may be additional release if we discover important security issues that warrant it'?

I appreciate if it is too much effort for such an old version of PHP, however upgrading to newer version is a bigger task in some cases.

**Comment by gplessis** [comment]
Why duplicate the effort while Debian already offers the latest PHP 5.4 version with security backports?

You should be able to able to get rid of this award situation by apt-pinning your PHP packages to use Debian's one.

**Comment by mig5** [comment]
If it can be solved with apt pinning then that's perfect and I agree no need to duplicate effort. I had tried with pinning but couldn't get it to work, probably got the syntax wrong. So a blog post would be great help, thanks!
