### ISSUE TITLE
Syncing 7.0.3-6 after importing 7.0.7

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-php#135]
You've imported Upstream version 7.0.7 in https://github.com/gplessis/dotdeb-php/commit/8a7fdfec6180d0a738f86e985f6814c9ce355b81
and synced to Debian's 7.0.3-6 in https://github.com/gplessis/dotdeb-php/commit/d5f8f56bd77dbad85247386761e606cff876c944

Could you resync with https://anonscm.debian.org/cgit/pkg-php/php.git/tree/ ?

**Comment by gplessis** [comment]
https://github.com/gplessis/dotdeb-php/commit/d5f8f56bd77dbad85247386761e606cff876c944 is based on 7.0.7-4 from Debian, not 7.0.3-6.

**Comment by szepeviktor** [comment]
Really. Sorry.

**Comment by szepeviktor** [comment]
In php7.0-common version 7.0.8-1~dotdeb+8.1 `/usr/share/doc/php7.0-common/NEWS.Debian.gz` contains

`php7.0 (7.0.3-6) unstable; urgency=medium`
https://github.com/gplessis/dotdeb-php/blob/master-7.0/jessie/debian/NEWS#L1

Shouldn't it be `7.0.8-1`?

**Comment by szepeviktor** [comment]
I see these changes are really from 7.0.3-6
http://metadata.ftp-master.debian.org/changelogs//main/p/php7.0/php7.0_7.0.8-2_changelog
Could it be that you have not imported them till 7.0.8?
