### ISSUE TITLE
igbinary session support?

### ISSUE THREAD

**Issue by kkretsch** [gplessis/dotdeb-php#137]
If I try to enable the current (PHP 7.0.8-1~dotdeb+8.1) php7 runtime my TYPO3 throws this error:

> PHP Warning: session_start(): Cannot find serialization handler 'igbinary' - session startup failed in /var/www/typo3_src-7.6.9/typo3/sysext/backend/Classes/Controller/LoginController.php line 93

The igbinary module is installed (cli and fpm configuration both use the igbinary.ini):

> # php -i|grep igbinary
> Additional .ini files parsed => /etc/php/7.0/cli/conf.d/10-igbinary.ini,
> igbinary
> igbinary support => enabled
> igbinary version => 1.2.2-dev
> igbinary APC serializer ABI => no
> igbinary session support => no
> igbinary.compact_strings => On => On
> session.serialize_handler => igbinary => igbinary

But it doesn't seem to support session handling.

As my TYPO3 site relies on a redis cache I have to enable the php7.0-redis module which in turn uses/needs the php7.0-igbinary module.

Any idea how I can combine those to a running mix?

Currently I still use a self compiled php7 version withour any igbinary which runs OK.

**Comment by gplessis** [comment]
Could you please try to set `session.serialize_handler` to anything else than igbinary? `php_serialize`, `php`, `php_binary` or `wddx` (just make sure you installed `php7.0-xml`for this last one), whatever suits your needs.

**Comment by kkretsch** [comment]
I tried that switching to php_binary and got:

> PHP Warning: igbinary_unserialize_header: unsupported version: 1631203895, should be 1 or 2 in /var/www/typo3_src-7.6.9/typo3/sysext/core/Classes/Cache/Frontend/VariableFrontend.php line 102

as the next error. Even cleaning all redis data didn't help. Or does it read some other source?

**Comment by gplessis** [comment]
Unfortunately, it's an [upstream issue](https://github.com/igbinary/igbinary/issues/20). We should both keep an eye on it.

I'll provide new igbinary packages as soon as : 
* this upstream issue is fixed
* or if session serialization is finally supported.
