### ISSUE TITLE
[Urgent] Why php70-xml version 7.0.6 and anterior have been removed from Dotdeb repository ?

### ISSUE THREAD

**Issue by AlexandreHagen** [gplessis/dotdeb-php#138]
Hi 

I have need php70-xml version 7.0.6 for my project ! But this version is not found in Dotdeb repository
(http://packages.dotdeb.org/pool/all/p/php7.0/).
It has been removed recently. I have need it because Php 7.0.7 and more have Memory leaks (see https://bugs.php.net/bug.php?id=71737)  

Could you please correct that ?

**Comment by gplessis** [comment]
They have not been removed : https://packages.dotdeb.org/pool/all/p/php7.0/

And they're still installable via apt-get by specifying the version number
