### ISSUE TITLE
no php7.0-dbg for php 7.0.8

### ISSUE THREAD

**Issue by jonashrem** [gplessis/dotdeb-php#141]
Highest available version of p7.0-dbg is 7.0.7-1 but other  php7 packages are build against 7.0.8-1~dotdeb+8.1

**Comment by jonashrem** [comment]
@gplessis 

Any change you look at this?

php7-dbg is still missing since 7.0.8

Is there anything I can do to help here?

**Comment by gplessis** [comment]
I should have some spare time this week-end to take aq look at this issue. I'll keep you posted.

**Comment by jonashrem** [comment]
thanks a lot. I appreciate this very much

**Comment by gplessis** [comment]
php-dbf is back with the latest PHP 7.0.12 packages.

**Comment by jonashrem** [comment]
Thank's a lot. This is very helpfull
