### ISSUE TITLE
missing detailed docs/package listings 

### ISSUE THREAD

**Issue by flobee** [gplessis/dotdeb-php#142]
Hi while planing/managing to switch to dotdeb-php with jessie, i miss the complete list of extensions. 
On the website imagick of xhprof extensions are listed but i miss them here:
https://github.com/gplessis/dotdeb-php/blob/master-7.0/jessie/EXTENSIONS
Kind regards flobee

**Comment by gplessis** [comment]
`apt-cache search php7.0` will give you the best listing possible.

**Comment by flobee** [comment]
Hi, yes but for planing, shell access must not be available :-)
