### ISSUE TITLE
Segmentation faults with 7.0.7-1~dotdeb+8.1

### ISSUE THREAD

**Issue by smelchior** [gplessis/dotdeb-php#144]
Hi,

we are getting Segmentation fault (11) using PHP 7.0.7-1~dotdeb+8.1 (cli).

What is your distribution? Debian 8 (8.4 Jessie)
What is your architecture? amd64
Which exact PHP version are you using? 7.0.7-1~dotdeb+8.1
Which SAPI are you using? cli
What’s the full content of your /etc/apt/sources.list and /etc/apt/sources.list.d files?
```
deb http://ftp.debian.org/debian jessie main non-free contrib
deb http://security.debian.org/ jessie/updates main non-free contrib

deb http://packages.dotdeb.org jessie all
deb-src http://packages.dotdeb.org jessie all
```
What is the result of dpkg -l 'php*' | grep '^.i' ?
```
ii  php-common       1:42-1~dotdeb+8.1            all          Common files for PHP packages
ii  php7.0-cli       7.0.7-1~dotdeb+8.1           amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common    7.0.7-1~dotdeb+8.1           all          Common files for packages built from the PHP source
ii  php7.0-dbg       7.0.7-1~dotdeb+8.1           amd64        Debug symbols for PHP7.0
ii  php7.0-igbinary  1.2.1-1~2b7c703-1~dotdeb+8.2 amd64        igbinary serializer for PHP
ii  php7.0-json      7.0.7-1~dotdeb+8.1           amd64        JSON module for PHP
ii  php7.0-memcached 2.2.0-2-52c644b-1~dotdeb+8.2 amd64        memcached extension module for PHP, uses libmemcached
ii  php7.0-msgpack   2.0.1-1~dotdeb+8.2           amd64        MessagePack serializer for PHP
ii  php7.0-opcache   7.0.7-1~dotdeb+8.1           amd64        Zend OpCache module for PHP
ii  php7.0-pgsql     7.0.7-1~dotdeb+8.1           amd64        PostgreSQL module for PHP
````
Please provide a textual description of the bug (don’t hesitate to provide some code, the expected result…).

reproducible segfaults upon executing a special cli script based on symfony 3
```
Aug  6 06:43:39 webn4 kernel: php[24173]: segfault at 78 ip 00000000005f223f sp 00007ffd8ba66370 error 4 in php7.0[400000+94f000]
Aug  6 06:44:02 webn4 kernel: php[24186]: segfault at 78 ip 00000000005f223f sp 00007ffdbe76d6a0 error 4 in php7.0[400000+94f000]
Aug  6 06:44:48 webn4 kernel: traps: php[24830] general protection ip:709291 sp:7ffccc4f7108 error:0 in php7.0[400000+94f000]
Aug  6 06:45:44 webn4 kernel: traps: php[24841] general protection ip:709291 sp:7ffcf404fea8 error:0 in php7.0[400000+94f000]
```

Please provide a backtrace, after installing php5-dbg.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Start Job
Program received signal SIGSEGV, Segmentation fault.
zend_mm_alloc_small (size=56, bin_num=6, heap=0x7ffff5200040) at /usr/src/builddir/Zend/zend_alloc.c:1295
1295	/usr/src/builddir/Zend/zend_alloc.c: No such file or directory.
```

Any idea what is causing this? The same happens in 7.0.9 but there are no debug symbols available for that version so we downgraded to create this report.

**Comment by gplessis** [comment]
Could you please try to download and install libpcre3 from this archive ([pcre3-8.38.zip](https://github.com/gplessis/dotdeb-php/files/344049/pcre3-8.38.zip))? It contains a backport of libpcre3 from Stretch to Jessie that could potentially solve your issue (see #124). Could you please test it and let me know if it solves your issue?

**Comment by smelchior** [comment]
I tried, unfortunately the same segfault still happens :(

**Comment by mente** [comment]
@gplessis is it possible to rebuild latest igbinary? Guess the issue was fixed, check igbinary/igbinary#58

**Comment by gplessis** [comment]
My latest actions were :
* packaging the latest PHP 7.0 version, with a new `php7.0-dbg` package
* upload a backport of pcre 8.39
* package the latest `php7.0-igbnary` version as referenced here

Could you please re-test and let me know if your issue has been fixed? If not, please provide a backtrace.

**Comment by gplessis** [comment]
Any feedback?

**Comment by mig5** [comment]
New version of php-igbinary might've introduced other problems? See #152

**Comment by smelchior** [comment]
sorry for the late reply, for me the issue is fixed, i cannot currently reproduce it

**Comment by prebenlm** [comment]
Did you do anything specific to resolve it @smelchior ? Because I experience an segmentation fault in a cli script as well, with PHP 7.1.

**Comment by smelchior** [comment]
With the version with the pcre backport, it worked. We switched to the https://deb.sury.org/ packages for 7.1 by now.
