### ISSUE TITLE
Can't figure out why I'm getting dependency issues with libssl-dev

### ISSUE THREAD

**Issue by geerlingguy** [gplessis/dotdeb-php#146]
After enabling dotdeb on Debian 8 Jessie (minimal) in Docker, then running `sudo apt-get -y install libssl-dev`, I get:

```
apt-get -y install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.0.0 (= 1.0.1t-1+deb8u2) but 1.0.2h-1~bpo8+2 is to be installed
              Recommends: libssl-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Stepping back, I found I needed to install libssl-dev when I first tried installing PHP 7.0 like so:

```
sudo apt-get -y install php7.0-common php7.0-cli libssl-dev php7.0-dev php7.0-fpm libpcre3-dev php7.0-opcache php7.0-apcu
```

This gave the message:

```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.0.0 (= 1.0.1t-1+deb8u2) but 1.0.2h-1~bpo8+2 is to be installed
              Recommends: libssl-doc but it is not going to be installed

Unable to correct problems, you have held broken packages.
```

Using aptitude gives no better help with the dependency/install:

```
aptitude -y install libssl-dev
The following NEW packages will be installed:
  libc-dev-bin{a} libc6-dev{a} libssl-dev{b} libssl-doc{a} linux-libc-dev{a} manpages{a} manpages-dev{a} 
  zlib1g-dev{a} 
0 packages upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 8792 kB of archives. After unpacking 27.6 MB will be used.
The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.0.0 (= 1.0.1t-1+deb8u2) but 1.0.2h-1~bpo8+2 is installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     libssl-dev [Not Installed]                         



No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

Note that on a fresh image / docker run, I still get similar errors when trying to install `libssl-dev`. I'm investigating what's wrong with the Debian Jessie install now, but wanted to put this in the issue queue since it's taken me some time digging, and I have noticed the same/similar error messages from a number of other people in blog posts / forum topics without any response (with regard to installing later PHP versions using dotdeb).

**Comment by geerlingguy** [comment]
Apparently this isn't an issue with the official Debian Docker image (https://github.com/docker-library/official-images/blob/master/library/debian):

  1. `docker pull debian:jessie`
  2. `docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro debian:jessie /lib/systemd/systemd`
  3. `docker exec --tty [id] env TERM=xterm apt-get -y update`
  4. `docker exec --tty [id] env TERM=xterm apt-get -y install libssl-dev`

This works and installs `libssl-dev:amd64 (1.0.1t-1+deb8u2)`.

So it must be my Docker image that builds on top of Debian Jessie :( Will open an issue in that repo instead, since it looks like it's not DotDeb's fault.

**Comment by desmax** [comment]
@geerlingguy have you figured it out?

**Comment by joolswills** [comment]
Did you install something from backports that installed a libssl from backports ? try installing libssl-dev from jessie-backports also.

**Comment by Aspect9** [comment]
hey Yonny Yo! installed!
