### ISSUE TITLE
php7.0-dbg is not updated since 7.0.7

### ISSUE THREAD

**Issue by mente** [gplessis/dotdeb-php#147]
Is there a chance to get it updated to latest upstream?

There was a [comment](https://www.dotdeb.org/2016/06/24/php-7-0-8-for-jessie/#comment-35302) in 7.0.8 release that dbg package is broken but without any reaction

**Comment by MatthiasKuehneEllerhold** [comment]
The newest release (0.4.0) of php7.0-dbg is from May 2014: https://github.com/krakjoe/phpdbg/releases . Even on their webseite 0.4.0 is the newest version.
But `phpdbg --version` (installed through dotdeb repositories) shows this:
```
phpdbg 0.5.0
PHP 7.0.11-1~dotdeb+8.1, Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by rraptorr** [comment]
php7.0-phpdbg (a php debugger tool) has nothing to do with php7.0-dbg (gdb debugging symbols for php binaries).

**Comment by MatthiasKuehneEllerhold** [comment]
Oh ok, thanks for the clarification!

**Comment by Galixte** [comment]
Hi @gplessis,

could you take a look?

**Comment by gplessis** [comment]
Duplicates #141
