### ISSUE TITLE
Old packages in mirrors

### ISSUE THREAD

**Issue by Pavel-Novikov** [gplessis/dotdeb-php#148]
Old packages on mirrors 
For example on Poland
deb http://dotdeb.zendev.pl/ jessie all
deb-src http://dotdeb.zendev.pl/ jessie all

PHP 7.0.9-1~dotdeb+8.1 (cli) ( NTS )
But today from main repo:
PHP 7.0.12-1~dotdeb+8.1 (cli) ( NTS )

**Comment by gplessis** [comment]
Both ftp://download.srv.ro/pub/dotdeb and http://dotdeb.zendev.pl are not up-to-date. I'll contact their maintainers and I will remove them from the mirror list if I don't get any answer from them.

Thanks for your report.

**Comment by gplessis** [comment]
ftp://download.srv.ro/pub/dotdeb is outdated, its maintainer just confirmed he won't update it. I removed it from the list.

**Comment by gplessis** [comment]
These two mirrors have been removed from the list.
