### ISSUE TITLE
No 7.0 for wheezy?

### ISSUE THREAD

**Issue by Quix0r** [gplessis/dotdeb-php#149]
I currently use wheezy on my server. It currently runs 5.6-dotdeb but I may wish like to switch to 7.0 or at least try it out (e.g. lesser memory usage is very interesting as my server "only" has 8 GB).

So there is no official build for wheezy? Yes, I know. It is old, but reliable (which I cannot say about systemd and the neccessary switch from wheezy to jessie).

**Comment by gplessis** [comment]
Sorry, but I won't provide PHP 7.0 for Wheezy because its packaging scripts depend on Apache 2.4 and Wheezy only provides Apache 2.2.

For testing purpose, please consider using a Jessie chroot/container/VM.

**Comment by Quix0r** [comment]
At least I was able to build it and install it to /opt. :-/ It would save a lot memory.
