### ISSUE TITLE
Add php 7.1 version

### ISSUE THREAD

**Issue by evilebottnawi** [gplessis/dotdeb-php#155]

**Comment by ptondereau** [comment]
need! @gplessis

**Comment by szepeviktor** [comment]
Wait, there is no version yet to backport: https://packages.debian.org/sid/php7.1

**Comment by evilebottnawi** [comment]
@Stricted why dislike?

**Comment by Stricted** [comment]
because i dont see the point in this issue, @gplessis will do a release when he has time

**Comment by Igor-Yavych** [comment]
Yeah, that'd be great. 7.1 has lots of new things and bug features. Would be great to update asap

**Comment by bbashy** [comment]
Interested in getting 7.1 as well!

**Comment by CharlotteDunois** [comment]
I am interested in running PHP 7.1.

**Comment by mdrmdrmdr** [comment]
Would like to have PHP 7.1 on Raspberry (Jessie / armhf).
Currently only 7.0 is avaliable via http://repozytorium.mati75.eu/raspbian
Thanks!

**Comment by AlexGx** [comment]
Waiting for 7.1

**Comment by emielmolenaar** [comment]
This would be awesome!

**Comment by f1mishutka** [comment]
Can't wait for 7.1 on dotdeb! Really interested in it.

**Comment by ChrisWesterfield** [comment]
any updates?

**Comment by bbashy** [comment]
7.0 only has active support until 3rd Dec 2017.

**Comment by stephenreay** [comment]
FYI there is a 7.1 source package in Sid now: https://packages.debian.org/source/sid/php7.1

**Comment by ChrisWesterfield** [comment]
But these packages are for the unstable distribution only.
and stretch is already in feature freeze so it will not make it to the next stable release.
would be nice to have it from the dotted repository

**Comment by stephenreay** [comment]
I meant that they can be used as the basis for dotdeb packages.

**Comment by mente** [comment]
@gplessis please tell us what stops you from doing this and how we can help you. Don't leave us blind :(.

Thanks a lot!

**Comment by bbashy** [comment]
Time to fork this project!

**Comment by gplessis** [comment]
Hi Guys,

sorry for the late answer. I wrote a post about my decision to not provide PHP 7.1+ on Dotdeb : https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/

Sorry about that, but I think that's the best decision I could make for everyone. I hope that I can invest my spare time in contributing directly to Debian instead of duplicating Ondřej's effort.

Thanks for using Dotdeb.
