### ISSUE TITLE
GeoIP segfault

### ISSUE THREAD

**Issue by FlorentCoppint** [gplessis/dotdeb-php#156]
Hi everyone,

I think there's a bug in GeoIP module. I use version "1.1.1-1~dotdeb+8.1" from Dotdeb.

Until now, it needed a "GeoIPCity.dat" file to work, but now it needs a "GeoIP.dat". If it does not exist, an error occurs : 

PHP Warning:  geoip_country_name_by_name(): Required database not available at /var/www/piwik/misc/GeoIP.dat. in /root/geoip.php on line 2

When I make a symbolic link "ln -s GeoIPCity.dat GeoIP.dat", I got a "segmentation fault" on my PHP script.

Test script is simple : 

```
<?php
echo geoip_country_name_by_name('8.8.8.8');
?>
```

It was working a few days ago before upgrading packages..

Did I miss something ?

Thank you.

**Comment by rraptorr** [comment]
GeoIP.dat and GeoIPCity.dat are completely different databases, symlinking them will not work. The main database is GeoIP.dat from geoip-database Debian package. GeoIPCity.dat contains additional city information, comes from geoip-database-extra package and is not required.

Remove the symlink, as this won't work. Ensure that you have geoip-database installed and GeoIP.dat file is in place.

**Comment by FlorentCoppint** [comment]
Before, the module worked without a "GeoIP.dat" file.
I always had a single GeoIPCity.dat and all was going fine.
Now module requires a GeoIP.dat...

**Comment by rraptorr** [comment]
Well, then you have something seriously mixed up in your system. Probably you have installed the database files manually and mixed their names or something like that.

The geoip module (any version) only needs GeoIP.dat file for IP->country information. This can be easily checked in the source code and with strace. GeoIPCity.dat is only needed if you attempt to use city related functions, not for geoip_country_name_by_name().

**Comment by rraptorr** [comment]
Just install the geoip-database package which contains GeoIP.dat file. And remove the symlink, GeoIPCity.dat is a completely different, incompatible, database.

**Comment by FlorentCoppint** [comment]
I really don't understand something... I never ever used a GeoIP.dat file.
And every tutorials on the internet speaks about the "city" version, see for example on Piwik : http://piwik.org/faq/how-to/faq_164/
That's not the only one, every tutorials on the Internet said to download the City database.
That's what I always did and it worked until now...

**Comment by FlorentCoppint** [comment]
I never installed packages geoip-database or geoip-database-extra, I always downloaded files from Maxmind.

**Comment by rraptorr** [comment]
There are two databases:
- GeoIP.dat - contains IP -> country mapping, it is and always was required by geoip module
- GeoIPCity.dat - contains additional city information, it can be used by geoip module, but it is not required

The FAQ you have linked does not tell you to download city database. It clearly says:
"And finally, if you are using the GeoLite City database there is one more thing you need to do. The PECL extension won’t recognize the database if it’s named GeoLiteCity.dat so make sure it is named GeoIPCity.dat."

That means IF you are, in addition to main database, using City database, you must change its name. It does not tell you to just download City database.

geoip-database package in Debian contains GeoIP.dat file from MaxMind, packaged in Debian friendly way. Additionally geoip-database-extra contains GeoIPCity.dat

If you were installing files manually then you probably mixed something up, had GeoIP.dat file lying around somewhere or whatever. I really cannot tell.

The geoip module always required GeoIP.dat file. You can argue however long you want, but I've explained above how it works. There is no change in geoip module behaviour.

**Comment by gplessis** [comment]
@rraptorr thanks for helping @FlorentCoppint  :)
