### ISSUE TITLE
/etc/php/7.0/cli/php.ini  appears with  *.dll files ¿?¿?

### ISSUE THREAD

**Issue by ikarynerv** [gplessis/dotdeb-php#157]
fresh instalation of debian jessie ,  installed and this appears in /etc/php/7.0/cli/php.ini

;extension=php_bz2.dll
;extension=php_curl.dll
;extension=php_fileinfo.dll
;extension=php_ftp.dll
;extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll

...etc

**Comment by rraptorr** [comment]
What problem does it create? Those lines are commented out.

**Comment by gplessis** [comment]
Not an issue.

**Comment by ikarynerv** [comment]
dll files in debian?
