### ISSUE TITLE
[Question] How can we help to maintain?

### ISSUE THREAD

**Issue by wandersonwhcr** [gplessis/dotdeb-php#160]
Hello,

I just forked your repo and read the history with GitK. I tried to recreate the same structure with PHP 7.1. I don't know if it is correct, but when I try to create a PR, Github "ignores" merges with unrelated histories.

Is there a way to help you?

https://github.com/wandersonwhcr/dotdeb-php/tree/master-7.1/jessie

ty

**Comment by gplessis** [comment]
Thanks for your help. I made a decision about PHP 7.1. See #155. Feel free to use deb.sury.org.

**Comment by wandersonwhcr** [comment]
That's sad :cry: 

BTW, thank you for your effort building packages for us and good luck in your new projects ;)

**Comment by gplessis** [comment]
I know it's sad, it has been a difficult decision to make. But since the official maintainer already provides the packages, there's no point for me to duplicate the effort.

Thanks for using Dotdeb.

**Comment by wandersonwhcr** [comment]
yeah, it's understandable... :)
