### ISSUE TITLE
PHP 5 for stretch

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-php#161]
Does anyone know of PHP 5 for the next Debian release?

**Comment by gplessis** [comment]
PHP 5.6 has entered its "Security only" phase and will be EOL in December 2018 : https://secure.php.net/supported-versions.php

Debian developers decided to move away from PHP5 after Jessie : https://packages.debian.org/search?keywords=php5

That means that you should be able to get PHP5 updates until Jessie reaches the end of its long term support (June 6, 2020) and use these packages on Stretch.

**Comment by szepeviktor** [comment]
Thank you.

It is easy to install php5-fpm but php5-dev a bit tricky as is dependencies.
