### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by j-schulz** [gplessis/dotdeb-php#162]
Hi,

it would be great if automatic updates could be run without interaction.

As example:

Configuration file '/etc/php/7.0/fpm/pool.d/www.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** www.conf (Y/I/N/O/D/Z) [default=N] ?

After that a menu opens and the user has to interact. Is it possible to kick that?

Regards
Jonny

**Comment by rraptorr** [comment]
Run

  apt-get update --assume-yes

or

  apt-get update --assume-no

Whatever your preference.

**Comment by j-schulz** [comment]
Yes I did that but it doesn't prevent the question if I want to replace the configuration file.

**Comment by rraptorr** [comment]
Well, then play with other apt options, this has hardly anything to do with dotdeb anyway. Try --force-yes or look in the apt man pages for other options that fit whatever you want to do.

**Comment by rraptorr** [comment]
Or something like:

    -o 'DPkg::Options::=--force-confold'
    -o 'DPkg::Options::=--force-confnew'
    -o 'DPkg::Options::=--force-confdef'
