### ISSUE TITLE
access to archive repositories? how

### ISSUE THREAD

**Issue by mckaygerhard** [gplessis/dotdeb-php#164]
hello i wish to know how can i access to archived repositories.. i mean https://archives.dotdeb.org

due we have some virtual environment with some php complicated software tha tonly runs on php 5.3 and 5.2 and migrating effors can take a big longer.. 

thanks in advanced

**Comment by gplessis** [comment]
Because of bad package naming conventions back then, http://archives.dotdeb.org can not be a proper repository, you can not add it to your sources.list. You have to download the packages manually from it.

**Comment by mckaygerhard** [comment]
O.o !!!!

ok thankyou for the info (sorry for issue in github but you dont have another place to ask in dotdeb page)

**Comment by mckaygerhard** [comment]
hi @gplessis sorry to post here in a old topic, but its due to not make more noise innecesary:

the archived and older releases of dotdeb will be erased some day? if yes, there's any plans to archived in some place!

for educationall and resurection purposes are very very practicall and solved many problems!

**Comment by gplessis** [comment]
@mckaygerhard I'll make sure that packages and archives stay online as long as possible. But maybe you should consider [mirroring the main repo](https://www.dotdeb.org/2008/08/25/mirroring-dotdeb/).

**Comment by mckaygerhard** [comment]
> But maybe you should consider mirroring the main repo.

O.o 

ok so dont be forever! umm i must start to find some place due i not have infraestructure for that.. thanks for answering!
