### ISSUE TITLE
Will the be Debian 9 Support?

### ISSUE THREAD

**Issue by mightyBroccoli** [gplessis/dotdeb-php#165]

**Comment by divinity76** [comment]
Debian 9 runs with PHP 7.0, with no intentions of upgrading to php 7.1/7.2 until debian 10, food for thought.

**Comment by divinity76** [comment]
for those looking for a debian 8 AND 9 repo for php7.0, 7.1, and 7.2, can check out sury.org

**Comment by Galixte** [comment]
Thanks 👍
