### ISSUE TITLE
PHP 5.6.31 has been released

### ISSUE THREAD

**Issue by kosli** [gplessis/dotdeb-php#166]
PHP 5.6.31 has been released a few days ago and would be nice to see it in DotDeb. Thanks for the great work. 
http://php.net/ChangeLog-5.php#5.6.31

**Comment by Galixte** [comment]
Done 👍 https://github.com/gplessis/dotdeb-php/blob/master-5.6/wheezy/debian/changelog thanks @gplessis ;)

**Comment by gplessis** [comment]
It's building now, but I'm abroad with a weak connection. I'll do my best to publish it asap.

**Comment by kosli** [comment]
wow, that was fast! thanks a lot.

**Comment by Galixte** [comment]
Now it’s done, thanks you Monsieur Plessis !

**Comment by gplessis** [comment]
You're welcome
