### ISSUE TITLE
nay way to provide php 5.6 for strecht debian 9?

### ISSUE THREAD

**Issue by mckaygerhard** [gplessis/dotdeb-php#169]
as we already know not all php software are up to work with php 7.X so and due php 5.6 still are supported i ask:

**its there any way to plan to provide php 5.6 for debian 9?** this due debian 9 by defaults ship with php 7.X and **many software doe snot work with that version!**

**Comment by gplessis** [comment]
I have no plan for this because:
* PHP 5.6 will reach its EOL at the end of this year
* Dotdeb does not support Stretch (yet, and probably never)

The best solution for you would be to mix Wheezy and Stretch entries to make PHP 5.6 packages (+ their dependencies) installable on Stretch.

**Comment by mckaygerhard** [comment]
> Dotdeb does not support Stretch (yet, and probably never)

makes sense, this project its to support newer php to older releases, 

> The best solution for you would be to mix Wheezy and Stretch entries to make PHP 5.6 packages (+ their dependencies) installable on Stretch.

i guess you means jessie and strecht.. jejej, ok thanks for answered! bye.
