### ISSUE TITLE
Feature/wishlist request: php-zeroc-ice support

### ISSUE THREAD

**Issue by NielsH** [gplessis/dotdeb-php#38]
Hello,

I've been using dotdeb for quite a while. For a server I run I need to communicate with ICE services. This can be done with php-zeroc-ice. Unfortunately dotdeb doesn't offer this package. My request is to add this package to the dotdeb repository.

http://www.zeroc.com/icephp.html
http://packages.debian.org/stable/php/php-zeroc-ice

Thank you,
Niels

**Comment by bestxp** [comment]
i have same troubles with installation of php-zeroc-ice 

```
dpkg-source -b php-zeroc-ice
dpkg-source: error: cannot stat directory php-zeroc-ice: No such file or directory
```

**Comment by gplessis** [comment]
Closing this old issue since since the currently provided PHP versions are reaching their EOL [next month](http://php.net/supported-versions.php).
