### ISSUE TITLE
Feature request: enable pty in proc_open

### ISSUE THREAD

**Issue by DennisBirkholz** [gplessis/dotdeb-php#49]
PHP contains the code to use PTYs instead of files for the file handles supplied to the process started.
The code is disabled but I use it and it seems stable enough. It is not documented (only in a comment) so it will only be used by people who know that ptys are possible.
In addition, the proc_open function is unlikely to be used in web scripts and should only be used in cli scripts.

The following patch will enable ptys in proc_open. Please consider including it, thanks!
# Index: src/ext/standard/proc_open.c

--- src/ext/standard/proc_open.c        (Revision 58)
+++ src/ext/standard/proc_open.c        (Arbeitskopie)
@@ -61,7 +61,7 @@
- */
  #ifdef PHP_CAN_SUPPORT_PROC_OPEN

-#if 0 && HAVE_PTSNAME && HAVE_GRANTPT && HAVE_UNLOCKPT && HAVE_SYS_IOCTL_H && HAVE_TERMIOS_H
+#if HAVE_PTSNAME && HAVE_GRANTPT && HAVE_UNLOCKPT && HAVE_SYS_IOCTL_H && HAVE_TERMIOS_H
 # include <sys/ioctl.h>
 # include <termios.h>
 # define PHP_CAN_DO_PTS        1

**Comment by gplessis** [comment]
Closing this issue since since the currently provided PHP versions are reaching their EOL [next month](http://php.net/supported-versions.php).
