### ISSUE TITLE
Feature request: phpiredis extension

### ISSUE THREAD

**Issue by theUniC** [gplessis/dotdeb-php#61]
Hi,

I think would be nice to provide support for the _phpiredis_ extension which is a wrapper around the _hiredis_ client, the official redis client.

**http://github.com/nrk/phpiredis**
**https://github.com/redis/hiredis**

Christian.

**Comment by PunKeel** [comment]
:+1: :)

**Comment by mente** [comment]
@gplessis any help needed? What's the policy for providing additional packages like this?

**Comment by gplessis** [comment]
Closing this issue since since the currently provided PHP versions are reaching their EOL [next month](http://php.net/supported-versions.php). Sorry :/
