### ISSUE TITLE
Segfault when producing notices when upstream closed the connection

### ISSUE THREAD

**Issue by sloonz** [gplessis/dotdeb-php#86]
On a nginx + php-fpm setup, where nginx has a low fastcgi_read_timeout, any script trying to write something on FCGI_STDERR will crash after the timeout occurs.

Steps to reproduce:

1. With nginx, set fastcgi_read_timeout to 3
2. Try the following script : 

    error_reporting(E_ALL);sleep(10);for($i=0;$i<200;$i++) $y = $x + 1;

3. Crash

With gdb, I have the following backtrace : 

	(gdb) bt
	#0  zend_hash_destroy (ht=0x1000701) at /usr/src/builddir/Zend/zend_hash.c:555
	#1  0x0000000000795eb1 in fcgi_close (req=0x7ffdf1252a60, force=<optimized out>, destroy=<optimized out>) at /usr/src/builddir/sapi/fpm/fpm/fastcgi.c:719
	#2  0x0000000000796910 in fcgi_finish_request (req=0x7ffdf1252a60, force_close=force_close@entry=0) at /usr/src/builddir/sapi/fpm/fpm/fastcgi.c:1046
	#3  0x000000000079e2ee in sapi_cgi_deactivate () at /usr/src/builddir/sapi/fpm/fpm/fpm_main.c:847
	#4  sapi_cgi_deactivate () at /usr/src/builddir/sapi/fpm/fpm/fpm_main.c:836
	#5  0x000000000069490d in sapi_deactivate () at /usr/src/builddir/main/SAPI.c:536
	#6  0x000000000068c0b5 in php_request_shutdown (dummy=dummy@entry=0x0) at /usr/src/builddir/main/main.c:1817
	#7  0x00000000004324a1 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/builddir/sapi/fpm/fpm/fpm_main.c:1966

But I suspect a memory corruption far before request_shutdown, since the script that initally led me to investigate this bug, which does some complex things after emitting notices has an entirely different one : 

	#0  open_packet (type=FCGI_STDERR, req=<optimized out>) at /usr/src/builddir/sapi/fpm/fpm/fastcgi.c:910
	#1  fcgi_write (req=req@entry=0x7ffd89dd9e30, type=type@entry=FCGI_STDERR, 
	    str=str@entry=0x27e23d0 "PHP message: PHP Notice:  Undefined offset: 0 in /home/dev/htdocs/includes/functions/makeemailsend.inc.php on line 322\n", len=len@entry=134) at /usr/src/builddir/sapi/fpm/fpm/fastcgi.c:981
	#2  0x000000000079db3b in sapi_cgi_log_fastcgi (level=<optimized out>, message=<optimized out>, len=133) at /usr/src/builddir/sapi/fpm/fpm/fpm_main.c:675
	#3  0x00000000007a4fb7 in zlog_ex (function=0xb92680 "sapi_cgi_log_message", line=685, flags=2, fmt=0xb91988 "PHP message: %s") at /usr/src/builddir/sapi/fpm/fpm/zlog.c:119
	#4  0x000000000068a228 in php_log_err (log_message=0x3389730 "PHP Notice:  Undefined offset: 0 in /home/dev/htdocs/includes/functions/makeemailsend.inc.php on line 322") at /usr/src/builddir/main/main.c:661
	#5  0x000000000068a5c7 in php_error_cb (type=8, error_filename=0x7f71eead0fa8 "/home/dev/htdocs/includes/functions/makeemailsend.inc.php", error_lineno=322, format=<optimized out>, args=<optimized out>)
	    at /usr/src/builddir/main/main.c:1074
	#6  0x00000000005a6030 in soap_error_handler (error_num=8, error_filename=0x7f71eead0fa8 "/home/dev/htdocs/includes/functions/makeemailsend.inc.php", error_lineno=322, format=0xb5c70d "Undefined offset: %ld", 
	    args=0x7ffd89dd75b0) at /usr/src/builddir/ext/soap/soap.c:2212
	#7  0x00000000006eca5e in zend_error (type=type@entry=8, format=format@entry=0xb5c70d "Undefined offset: %ld") at /usr/src/builddir/Zend/zend.c:1214
	#8  0x0000000000774192 in zend_fetch_dimension_address_inner (type=0, dim_type=<optimized out>, dim=<optimized out>, ht=0x7f71f06cd8a8) at /usr/src/builddir/Zend/zend_execute.c:1059
	#9  zend_fetch_dimension_address_read (result=0x7f71fa947c50, container=<optimized out>, dim=dim@entry=0x7f71ee8d52c0, dim_type=dim_type@entry=4, type=type@entry=0) at /usr/src/builddir/Zend/zend_execute.c:1258
	#10 0x000000000077515f in ZEND_FETCH_DIM_R_SPEC_CV_VAR_HANDLER (execute_data=0x7f71fa9440f0) at /usr/src/builddir/Zend/zend_vm_execute.h:32628
	#11 0x000000000074d747 in execute (op_array=0x7f71f0700a70) at /usr/src/builddir/Zend/zend_vm_execute.h:410
	#12 0x00000000006ed57c in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /usr/src/builddir/Zend/zend.c:1329
	#13 0x000000000068d2e3 in php_execute_script (primary_file=primary_file@entry=0x7ffd89dd9c10) at /usr/src/builddir/main/main.c:2502
	#14 0x0000000000432afa in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/builddir/sapi/fpm/fpm/fpm_main.c:1938

**Comment by gplessis** [comment]
I don't think this is a Dotdeb-specific problem. Could you please open a ticket on http://bugs.php.net/ ?

**Comment by gplessis** [comment]
Hmmm, does it happen without Xdebug? Could you please give me more details on your setup (see https://www.dotdeb.org/2012/08/24/how-to-post-useful-bug-reports/) ?

**Comment by sloonz** [comment]
Yes, it happens without xdebug too. I edited the second backtrace after getting rid of it.

Debian Wheezy, amd64. Package list : 

	ii  php-file-iterator                      1.3.1-2                                all          FilterIterator implementation for PHP
	ii  php-invoker                            1.1.0-1                                all          utility class for invoking callables with a timeout
	ii  php-pear                               5.4.41-1~dotdeb+7.1                    all          PEAR - PHP Extension and Application Repository
	ii  php-symfony-yaml                       1.0.6-1                                all          Symfony YAML: A PHP library that speaks YAML
	ii  php-text-template                      1.1.1-2                                all          Simple php template engine
	ii  php-timer                              1.0.2-2                                all          PHP Utility class for timing
	ii  php-token-stream                       1.1.3-2                                all          Wrapper around PHP's tokenizer extension
	ii  php5                                   5.4.41-1~dotdeb+7.1                    all          server-side, HTML-embedded scripting language (metapackage)
	ii  php5-cli                               5.4.41-1~dotdeb+7.1                    amd64        command-line interpreter for the php5 scripting language
	ii  php5-common                            5.4.41-1~dotdeb+7.1                    amd64        Common files for packages built from the php5 source
	ii  php5-curl                              5.4.41-1~dotdeb+7.1                    amd64        CURL module for php5
	ii  php5-dbg                               5.4.41-1~dotdeb+7.1                    amd64        Debug symbols for PHP5
	ii  php5-fpm                               5.4.41-1~dotdeb+7.1                    amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
	ii  php5-gd                                5.4.41-1~dotdeb+7.1                    amd64        GD module for php5
	ii  php5-gmp                               5.4.41-1~dotdeb+7.1                    amd64        GMP module for php5
	ii  php5-ldap                              5.4.41-1~dotdeb+7.1                    amd64        LDAP module for php5
	ii  php5-mcrypt                            5.4.41-1~dotdeb+7.1                    amd64        MCrypt module for php5
	ii  php5-memcache                          5.4.41-1~dotdeb+7.1                    amd64        memcache module for php5
	ii  php5-memcached                         5.4.41-1~dotdeb+7.1                    amd64        memcached module for php5
	ii  php5-mysqlnd                           5.4.41-1~dotdeb+7.1                    amd64        MySQL module for php5 (Native Driver)
	ii  php5-sqlite                            5.4.41-1~dotdeb+7.1                    amd64        SQLite module for php5
	ii  phpunit-mock-object                    1.1.1-2                                all          Mock Object library for PHPUnit
	ii  phpunit-story                          1.0.0-3                                all          extension to facilitate Behaviour-Driven Development
