### ISSUE TITLE
opcache.huge_code_page + s

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-php#93]
... as commented
https://www.dotdeb.org/2015/09/18/php-7-0-rc3-for-jessie/#comment-34696

**Comment by szepeviktor** [comment]
WP site: If you like the emoji script removed from your site: https://wordpress.org/plugins/classic-smilies/

**Comment by gplessis** [comment]
Fixed. Thanks.

**Comment by szepeviktor** [comment]
Could you purge W3 Total Cache?

**Comment by gplessis** [comment]
Done

**Comment by szepeviktor** [comment]
Thank you.
