### ISSUE TITLE
 Directory permissions on default session.save_path 

### ISSUE THREAD

**Issue by floydik** [gplessis/dotdeb-php#94]
After install php7 I have:

testovaci:/#  ls -ld /var/lib/php/sessions/
drwxr-xr-x 2 root root 6 Aug 31 04:17 /var/lib/php/sessions/
testovaci:/# stat /var/lib/php/sessions/
  File: '/var/lib/php/sessions/'
  Size: 6               Blocks: 0          IO Block: 4096   directory
Device: 801h/2049d      Inode: 4383459     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-10-01 12:10:04.244475321 +0200
Modify: 2015-08-31 04:17:36.000000000 +0200
Change: 2015-10-01 11:59:52.456463015 +0200
 Birth: -
testovaci:/#

That causes unable to start new session in default.
Previous version of PHP had:
root@greip:/# ls -ld /var/lib/php5/sessions/
drwx-wx-wt 2 root root 28672 Oct  1 12:24 /var/lib/php5/sessions/

PLS fix it. 
Thank you.

**Comment by Booteille** [comment]
I fixed it by giving server's permissions (default as www-data) to the folder.

**Comment by EAnushan** [comment]
You can run ```chmod 1733 /var/lib/php/sessions/``` to fix the issue for now. This will set the folder permissions to the same as what was set in PHP 5.

**Comment by gplessis** [comment]
The permissions of `/var/lib/php/sessions/` have been fixed in the latest upload.
