### ISSUE TITLE
php5-gd wrong dependencies 

### ISSUE THREAD

**Issue by flowl** [gplessis/dotdeb-php#95]
The following packages have unmet dependencies:
    php5-gd : Depends: libjpeg8 (>= 8c) but it is not installable
              Depends: libt1-5 (>= 5.1.0) but it is not installable

Available package is libjpeg-dev
I don't know what libt1 is.

Debian 8.2, PHP 5.6.14-1~dotdeb+zts+7.1 (cli)

**Comment by gplessis** [comment]
Dotdeb does not provide nor support PHP 5 packages for Jessie. Please stick to Debian stable + security for this, they already provide 5.6.14 with right dependencies : https://packages.debian.org/php5
