### ISSUE TITLE
PHP 7 packaging script

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-php#96]
Excuse me for the question.
Is the Debian packaging script for PHP 7 from php5?

**Comment by gplessis** [comment]
No, they are brand new. See the master-7.0/jessie branch for more details.

**Comment by szepeviktor** [comment]
THank you.
Found: https://packages.debian.org/experimental/php7.0

**Comment by gplessis** [comment]
Yes, Dotdeb packages are basically backports from Debian's php7.0 packages
