### ISSUE TITLE
build scripts for php7?

### ISSUE THREAD

**Issue by blindpet** [gplessis/dotdeb-php#97]
I'm trying to find your build scripts for php7, can you point me in the right direction?

**Comment by gplessis** [comment]
Everything is in the `debian/` subdirectories of : 
* https://github.com/gplessis/dotdeb-php/tree/master-7.0/jessie
* https://github.com/gplessis/dotdeb-php-modules/tree/master-7.0/jessie

You might want to use Docker to easily bootstrap a build environment (see `debian/Dockerfile.*`)

**Comment by blindpet** [comment]
It is for an arm device, I see all of the files but is there some bash script that will loop through and build everything?

**Comment by gplessis** [comment]
While in the root directory of your git clone, execute : 
```
apt-get update
apt-get dist-upgrade -y
apt-get install -y build-essential devscripts equivs libwww-perl curl
mk-build-deps --install --tool 'apt-get -y' --remove debian/control
curl -Lo ../php7.0_7.0.0~rc7.orig.tar.xz https://downloads.php.net/~ab/php-7.0.0RC7.tar.xz
dpkg-buildpackage
```
