### ISSUE TITLE
PHP7.0-fpm conflict in post-installation script

### ISSUE THREAD

**Issue by Booteille** [gplessis/dotdeb-php#98]
Hi.

I had this issue :
>insserv: script php7.0-fpm: service php-fpm already provided!

This is caused because I already have installed php5-fpm and this one already uses a service called php-fpm.

I just had to change this line in */etc/init.d/php7.0-fpm* in order to have no more error :
`# Provides:          php-fpm php7.0-fpm`
in
`# Provides:          php7-fpm php7.0-fpm`

Maybe this should be modified in the dotdeb version in order to not have more conflicts.

Thanks.

**Comment by gplessis** [comment]
There is now an explicit conflict between PHP5 and PHP7 packages to prevent this issue.

**Comment by Booteille** [comment]
Thanks. And thanks for the new php 7 package.
